version: '3'

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./website:/www
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - api
      - app
  api:
    image: mynode
    build:
      context: ./docker/node
    networks:
      - backend-network
    ports:
      - "8080:8080"
    environment:
      NODE_PORT: 8080
    volumes:
      - ./api:/app
    depends_on:
      - mongo
  app:
    image: mynode
    networks:
      - backend-network
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
  mongo:
    image: mongo:3
    networks:
      - backend-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
