export const authConstants = {
    SET_CURRENT_USER: 'AUTH_SET_CURRENT_USER',
    SET_TOKEN: 'AUTH_SET_TOKEN',
    LOGOUT: 'AUTH_LOGOUT',
    REFRESH_STARTED: 'AUTH_REFRESH_STARTED',
    REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
};
